language: java

sudo: required

services: 
  - neo4j

jdk:
  - oraclejdk8
  
install: /bin/true

before_install:
  - gradle wrapper
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  
before_script:
  - sleep 15
  - echo $JAVA_OPTS
  - export JAVA_OPTS=-Xmx512m
  - wget https://services.gradle.org/distributions/gradle-4.1-bin.zip
  - unzip gradle-4.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.1
  - export PATH=$GRADLE_HOME/bin:$PATH  
  
script:
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew codeCoverageReport
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml